import enum


class ShipmentStatus(str, enum.Enum):
    """运单在创建阶段使用的状态枚举。"""

    PENDING_PAYMENT = "PENDING_PAYMENT"
    PENDING_PICKUP = "PENDING_PICKUP"
    PICKUP_ASSIGNED = "PICKUP_ASSIGNED"
    WAITING_FOR_DROPOFF = "WAITING_FOR_DROPOFF"
    PICKED_UP = "PICKED_UP"
    AT_ORIGIN_STATION = "AT_ORIGIN_STATION"
    IN_LINEHAUL = "IN_LINEHAUL"
    AT_DESTINATION_STATION = "AT_DESTINATION_STATION"
    DELIVERY_ASSIGNED = "DELIVERY_ASSIGNED"
    OUT_FOR_DELIVERY = "OUT_FOR_DELIVERY"
    WAITING_FOR_RECIPIENT_PICKUP = "WAITING_FOR_RECIPIENT_PICKUP"
    DELIVERED = "DELIVERED"
    CANCELLED = "CANCELLED"


class PickupMethod(str, enum.Enum):
    """寄件端的交付方式。"""

    DOOR_PICKUP = "DOOR_PICKUP"
    STATION_DROPOFF = "STATION_DROPOFF"


class DeliveryMethod(str, enum.Enum):
    """收件端的交付方式。"""

    HOME_DELIVERY = "HOME_DELIVERY"
    STATION_PICKUP = "STATION_PICKUP"
