<script setup lang="ts">
import { computed, onMounted, ref, watch } from 'vue'
import { ElMessage } from 'element-plus'
import { CircleCheck, Connection, DataBoard, Document, Files, FolderOpened, Refresh, Search, Setting, UploadFilled, Warning } from '@element-plus/icons-vue'
import { knowledgeAction, listDeadLetters, listKnowledgeDocuments, replayDeadLetter, reviewKnowledgeDocument, searchKnowledge, uploadKnowledgeDocument, type DeadLetter, type KnowledgeDocument } from './api'

const props = defineProps<{ user: { display_name: string; role: string }; embedded?: boolean; initialView?: string }>()
defineEmits<{ logout: [] }>()

const view = ref('overview')
watch(() => props.initialView, (next) => { if (next) view.value = next }, { immediate: true })
const loading = ref(false)
const deadLetters = ref<DeadLetter[]>([])
const documents = ref<KnowledgeDocument[]>([])
const searchText = ref('')
const evidence = ref<any[]>([])
const uploadRef = ref<any>()
const reviewDialog = ref(false)
const selectedDocument = ref<KnowledgeDocument | null>(null)
const reviewForm = ref({ category: '', effective_from: '', effective_to: '' })
const nav = [{ id: 'overview', label: '系统概览', icon: DataBoard }, { id: 'deadletters', label: '死信队列', icon: Warning }, { id: 'knowledge', label: '知识库文档', icon: Files }, { id: 'retrieval', label: '检索验证', icon: Search }]
const pendingDeadLetters = computed(() => deadLetters.value.filter(item => !item.replayed_at))
const publishedDocuments = computed(() => documents.value.filter(item => item.status === 'PUBLISHED').length)

async function loadData() { loading.value = true; try { const [deadLetterItems, documentItems] = await Promise.all([listDeadLetters({ limit: 100, offset: 0 }), listKnowledgeDocuments({ limit: 100, offset: 0 })]); deadLetters.value = deadLetterItems; documents.value = documentItems } catch { ElMessage.error('系统运维数据加载失败') } finally { loading.value = false } }
async function replay(item: DeadLetter) { try { await replayDeadLetter(item.id); ElMessage.success('死信已重新投递'); await loadData() } catch (error: any) { ElMessage.error(error.response?.data?.message || '死信重放失败') } }
async function upload(request: { file: File }) { try { const document = await uploadKnowledgeDocument(request.file); documents.value = [document, ...documents.value]; ElMessage.success('文档已上传，正在进入解析队列') } catch (error: any) { ElMessage.error(error.response?.data?.message || '文档上传失败') } }
function openReview(item: KnowledgeDocument) { selectedDocument.value = item; reviewForm.value = { category: item.category || '', effective_from: '', effective_to: '' }; reviewDialog.value = true }
async function submitReview() { if (!selectedDocument.value) return; try { const updated = await reviewKnowledgeDocument(selectedDocument.value.id, { category: reviewForm.value.category || undefined, effective_from: reviewForm.value.effective_from || undefined, effective_to: reviewForm.value.effective_to || undefined }); updateDocument(updated); reviewDialog.value = false; ElMessage.success('审核信息已保存') } catch (error: any) { ElMessage.error(error.response?.data?.message || '审核保存失败') } }
async function documentAction(item: KnowledgeDocument, action: 'publish' | 'archive' | 'deactivate' | 'reparse') { try { updateDocument(await knowledgeAction(item.id, action)); ElMessage.success(action === 'publish' ? '文档已发布' : action === 'reparse' ? '已重新提交解析' : '文档状态已更新') } catch (error: any) { ElMessage.error(error.response?.data?.message || '操作失败，请检查文档当前状态') } }
function updateDocument(updated: KnowledgeDocument) { documents.value = documents.value.map(item => item.id === updated.id ? updated : item) }
async function runSearch() { if (!searchText.value.trim()) return; try { evidence.value = (await searchKnowledge(searchText.value.trim())).items } catch (error: any) { ElMessage.error(error.response?.data?.message || '知识检索失败') } }
function statusType(status: string) { return status === 'PUBLISHED' ? 'success' : status === 'PARSE_FAILED' ? 'danger' : status === 'REVIEW_REQUIRED' ? 'warning' : 'info' }
onMounted(loadData)
</script>

<template>
  <div :class="props.embedded ? 'system-embedded' : 'app-shell system-shell'"><aside v-if="!props.embedded" class="sidebar"><div class="logo"><span>Y</span><div>Yitu<small>物流工作台</small></div></div><div class="workspace-label">系统管理工作区</div><nav><button v-for="item in nav" :key="item.id" :class="{ active: view === item.id }" @click="view = item.id"><component :is="item.icon" /><span>{{ item.label }}</span><b v-if="item.id === 'deadletters' && pendingDeadLetters.length">{{ pendingDeadLetters.length }}</b></button></nav><div class="system-health"><small>服务运行状态</small><strong><i></i> 正常</strong><span>队列与对象存储可用</span></div><div class="sidebar-foot"><el-button text @click="$emit('logout')"><Setting /> 退出登录</el-button></div></aside>
    <main class="main"><header v-if="!props.embedded" class="topbar"><div><div class="crumb">系统运维 <span>/</span> {{ nav.find(item => item.id === view)?.label }}</div><h1>{{ nav.find(item => item.id === view)?.label }}</h1></div><div class="top-actions"><el-button circle :icon="Refresh" @click="loadData" /><el-avatar :size="34">{{ user.display_name.slice(0, 1) }}</el-avatar><span class="user-name">{{ user.display_name }}</span></div></header>
      <section v-loading="loading" class="content"><div class="page-block">
        <template v-if="view === 'overview'"><div class="system-hero"><div><p class="section-kicker">SYSTEM OPERATIONS</p><h2>稳定运行，持续可追溯</h2><p>监控异步事件、知识文档和检索链路的系统状态。</p></div><div class="system-emblem"><Connection /></div></div><div class="system-kpis"><div><small>待处理死信</small><strong>{{ pendingDeadLetters.length }}</strong><span>需要人工重放</span></div><div><small>本次管理文档</small><strong>{{ documents.length }}</strong><span>当前浏览器会话</span></div><div><small>已发布文档</small><strong>{{ publishedDocuments }}</strong><span>可参与 RAG 检索</span></div></div><div class="section-head compact"><div><p class="section-kicker">SYSTEM ALERTS</p><h2>需要关注</h2></div><el-button text type="primary" @click="view = 'deadletters'">查看死信队列</el-button></div><div class="sys-alerts"><article v-for="item in pendingDeadLetters.slice(0, 4)" :key="item.id"><Warning /><div><strong>{{ item.event_type }}</strong><p>{{ item.last_error }}</p><small>{{ item.business_id }} · 已尝试 {{ item.attempts }} 次</small></div><el-button type="primary" plain @click="replay(item)">重放</el-button></article><el-empty v-if="!pendingDeadLetters.length" description="没有待处理死信" /></div></template>
        <template v-else-if="view === 'deadletters'"><div class="section-head"><div><p class="section-kicker">ASYNC EVENT RECOVERY</p><h2>死信队列</h2></div><span class="mono-caption">{{ deadLetters.length }} 条记录</span></div><el-table :data="deadLetters" class="shipment-table"><el-table-column prop="event_type" label="事件类型" min-width="150" /><el-table-column prop="business_id" label="业务标识" min-width="160" /><el-table-column prop="attempts" label="尝试次数" width="90" /><el-table-column prop="last_error" label="最后错误" min-width="220" show-overflow-tooltip /><el-table-column prop="suggested_action" label="建议操作" min-width="150" /><el-table-column label="操作" width="110"><template #default="{ row }"><el-button v-if="!row.replayed_at" type="primary" size="small" @click="replay(row)">重新投递</el-button><el-tag v-else type="success" size="small">已重放</el-tag></template></el-table-column></el-table></template>
        <template v-else-if="view === 'knowledge'"><div class="section-head"><div><p class="section-kicker">KNOWLEDGE LIFECYCLE</p><h2>知识库文档</h2></div><el-upload ref="uploadRef" :show-file-list="false" accept="application/pdf,.pdf" :http-request="upload"><el-button type="primary"><UploadFilled /> 上传 PDF</el-button></el-upload></div><div class="knowledge-note"><FolderOpened /><span>上传后文档进入 MinerU 异步解析。此列表保留本次浏览器会话中上传或操作的文档。</span></div><div class="document-grid"><article v-for="item in documents" :key="item.id" class="document-card"><div class="doc-icon"><Document /></div><div class="doc-head"><div><h3>{{ item.filename }}</h3><small>{{ (item.size_bytes / 1024).toFixed(1) }} KB · {{ item.content_type }}</small></div><el-tag :type="statusType(item.status)">{{ item.status }}</el-tag></div><p v-if="item.error_message" class="doc-error">{{ item.error_message }}</p><dl><div><dt>分类</dt><dd>{{ item.category || '未分类' }}</dd></div><div><dt>页数</dt><dd>{{ item.page_count ?? '解析中' }}</dd></div><div><dt>解析任务</dt><dd>{{ item.mineru_task_id || '等待提交' }}</dd></div></dl><div class="doc-actions"><el-button size="small" @click="openReview(item)">审核信息</el-button><el-button v-if="item.status === 'REVIEW_REQUIRED'" type="primary" size="small" @click="documentAction(item, 'publish')">发布</el-button><el-button v-if="['PARSE_FAILED', 'ARCHIVED', 'DEACTIVATED'].includes(item.status)" size="small" @click="documentAction(item, 'reparse')">重新解析</el-button><el-button v-if="item.status === 'PUBLISHED'" type="warning" plain size="small" @click="documentAction(item, 'archive')">归档</el-button></div></article><el-empty v-if="!documents.length" description="上传第一份规则文档" /></div></template>
        <template v-else><div class="section-head"><div><p class="section-kicker">RAG RETRIEVAL CHECK</p><h2>检索验证</h2></div></div><div class="retrieval-search"><el-input v-model="searchText" size="large" placeholder="输入规则问题，例如：哪些物品禁止寄递？" @keyup.enter="runSearch" /><el-button type="primary" size="large" @click="runSearch"><Search /> 检索</el-button></div><div class="evidence-list"><article v-for="item in evidence" :key="`${item.document_id}-${item.score}`"><div class="evidence-score">{{ (item.score * 100).toFixed(0) }}</div><div><div class="evidence-head"><strong>{{ item.title || item.filename }}</strong><el-tag size="small" effect="plain">{{ item.category || '未分类' }}</el-tag></div><p>{{ item.content }}</p><small>{{ item.filename }} · {{ item.page_start ? `第 ${item.page_start}-${item.page_end || item.page_start} 页` : '无页码' }}</small></div></article><el-empty v-if="!evidence.length" description="输入问题后验证知识检索结果" /></div></template>
      </div></section>
    </main>
    <el-dialog v-model="reviewDialog" title="审核文档信息" width="480px"><el-form label-position="top"><el-form-item label="知识分类"><el-input v-model="reviewForm.category" placeholder="例如：禁寄规则" /></el-form-item><el-form-item label="生效时间"><el-date-picker v-model="reviewForm.effective_from" type="datetime" value-format="YYYY-MM-DDTHH:mm:ssZ" /></el-form-item><el-form-item label="失效时间"><el-date-picker v-model="reviewForm.effective_to" type="datetime" value-format="YYYY-MM-DDTHH:mm:ssZ" /></el-form-item></el-form><template #footer><el-button @click="reviewDialog = false">取消</el-button><el-button type="primary" @click="submitReview">保存审核</el-button></template></el-dialog>
  </div>
</template>
